# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/user16/workspace_vivado/basys3_exam/basys3_exam.srcs/sources_1/bd/soc_hello/ip/soc_hello_axi_smc_0/soc_hello_axi_smc_0.xci
# IP: The module: 'soc_hello_axi_smc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: /home/user16/workspace_vivado/basys3_exam/basys3_exam.gen/sources_1/bd/soc_hello/ip/soc_hello_axi_smc_0/bd_0/bd_57e4.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user16/workspace_vivado/basys3_exam/basys3_exam.gen/sources_1/bd/soc_hello/ip/soc_hello_axi_smc_0/bd_0/ip/ip_0/bd_57e4_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user16/workspace_vivado/basys3_exam/basys3_exam.gen/sources_1/bd/soc_hello/ip/soc_hello_axi_smc_0/bd_0/ip/ip_1/bd_57e4_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user16/workspace_vivado/basys3_exam/basys3_exam.gen/sources_1/bd/soc_hello/ip/soc_hello_axi_smc_0/bd_0/ip/ip_2/bd_57e4_arinsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user16/workspace_vivado/basys3_exam/basys3_exam.gen/sources_1/bd/soc_hello/ip/soc_hello_axi_smc_0/bd_0/ip/ip_3/bd_57e4_rinsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user16/workspace_vivado/basys3_exam/basys3_exam.gen/sources_1/bd/soc_hello/ip/soc_hello_axi_smc_0/bd_0/ip/ip_4/bd_57e4_awinsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user16/workspace_vivado/basys3_exam/basys3_exam.gen/sources_1/bd/soc_hello/ip/soc_hello_axi_smc_0/bd_0/ip/ip_5/bd_57e4_winsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user16/workspace_vivado/basys3_exam/basys3_exam.gen/sources_1/bd/soc_hello/ip/soc_hello_axi_smc_0/bd_0/ip/ip_6/bd_57e4_binsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user16/workspace_vivado/basys3_exam/basys3_exam.gen/sources_1/bd/soc_hello/ip/soc_hello_axi_smc_0/bd_0/ip/ip_7/bd_57e4_aroutsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user16/workspace_vivado/basys3_exam/basys3_exam.gen/sources_1/bd/soc_hello/ip/soc_hello_axi_smc_0/bd_0/ip/ip_8/bd_57e4_routsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user16/workspace_vivado/basys3_exam/basys3_exam.gen/sources_1/bd/soc_hello/ip/soc_hello_axi_smc_0/bd_0/ip/ip_9/bd_57e4_awoutsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user16/workspace_vivado/basys3_exam/basys3_exam.gen/sources_1/bd/soc_hello/ip/soc_hello_axi_smc_0/bd_0/ip/ip_10/bd_57e4_woutsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user16/workspace_vivado/basys3_exam/basys3_exam.gen/sources_1/bd/soc_hello/ip/soc_hello_axi_smc_0/bd_0/ip/ip_11/bd_57e4_boutsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user16/workspace_vivado/basys3_exam/basys3_exam.gen/sources_1/bd/soc_hello/ip/soc_hello_axi_smc_0/bd_0/ip/ip_12/bd_57e4_arni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user16/workspace_vivado/basys3_exam/basys3_exam.gen/sources_1/bd/soc_hello/ip/soc_hello_axi_smc_0/bd_0/ip/ip_13/bd_57e4_rni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user16/workspace_vivado/basys3_exam/basys3_exam.gen/sources_1/bd/soc_hello/ip/soc_hello_axi_smc_0/bd_0/ip/ip_14/bd_57e4_awni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user16/workspace_vivado/basys3_exam/basys3_exam.gen/sources_1/bd/soc_hello/ip/soc_hello_axi_smc_0/bd_0/ip/ip_15/bd_57e4_wni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user16/workspace_vivado/basys3_exam/basys3_exam.gen/sources_1/bd/soc_hello/ip/soc_hello_axi_smc_0/bd_0/ip/ip_16/bd_57e4_bni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user16/workspace_vivado/basys3_exam/basys3_exam.gen/sources_1/bd/soc_hello/ip/soc_hello_axi_smc_0/bd_0/ip/ip_17/bd_57e4_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user16/workspace_vivado/basys3_exam/basys3_exam.gen/sources_1/bd/soc_hello/ip/soc_hello_axi_smc_0/bd_0/ip/ip_18/bd_57e4_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user16/workspace_vivado/basys3_exam/basys3_exam.gen/sources_1/bd/soc_hello/ip/soc_hello_axi_smc_0/bd_0/ip/ip_19/bd_57e4_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user16/workspace_vivado/basys3_exam/basys3_exam.gen/sources_1/bd/soc_hello/ip/soc_hello_axi_smc_0/bd_0/ip/ip_20/bd_57e4_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user16/workspace_vivado/basys3_exam/basys3_exam.gen/sources_1/bd/soc_hello/ip/soc_hello_axi_smc_0/bd_0/ip/ip_21/bd_57e4_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user16/workspace_vivado/basys3_exam/basys3_exam.gen/sources_1/bd/soc_hello/ip/soc_hello_axi_smc_0/bd_0/ip/ip_22/bd_57e4_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user16/workspace_vivado/basys3_exam/basys3_exam.gen/sources_1/bd/soc_hello/ip/soc_hello_axi_smc_0/bd_0/ip/ip_23/bd_57e4_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user16/workspace_vivado/basys3_exam/basys3_exam.gen/sources_1/bd/soc_hello/ip/soc_hello_axi_smc_0/bd_0/ip/ip_24/bd_57e4_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user16/workspace_vivado/basys3_exam/basys3_exam.gen/sources_1/bd/soc_hello/ip/soc_hello_axi_smc_0/bd_0/ip/ip_25/bd_57e4_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user16/workspace_vivado/basys3_exam/basys3_exam.gen/sources_1/bd/soc_hello/ip/soc_hello_axi_smc_0/bd_0/ip/ip_26/bd_57e4_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user16/workspace_vivado/basys3_exam/basys3_exam.gen/sources_1/bd/soc_hello/ip/soc_hello_axi_smc_0/bd_0/ip/ip_27/bd_57e4_m00arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user16/workspace_vivado/basys3_exam/basys3_exam.gen/sources_1/bd/soc_hello/ip/soc_hello_axi_smc_0/bd_0/ip/ip_28/bd_57e4_m00rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user16/workspace_vivado/basys3_exam/basys3_exam.gen/sources_1/bd/soc_hello/ip/soc_hello_axi_smc_0/bd_0/ip/ip_29/bd_57e4_m00awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user16/workspace_vivado/basys3_exam/basys3_exam.gen/sources_1/bd/soc_hello/ip/soc_hello_axi_smc_0/bd_0/ip/ip_30/bd_57e4_m00wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user16/workspace_vivado/basys3_exam/basys3_exam.gen/sources_1/bd/soc_hello/ip/soc_hello_axi_smc_0/bd_0/ip/ip_31/bd_57e4_m00bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user16/workspace_vivado/basys3_exam/basys3_exam.gen/sources_1/bd/soc_hello/ip/soc_hello_axi_smc_0/bd_0/ip/ip_32/bd_57e4_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user16/workspace_vivado/basys3_exam/basys3_exam.gen/sources_1/bd/soc_hello/ip/soc_hello_axi_smc_0/bd_0/ip/ip_33/bd_57e4_m01s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user16/workspace_vivado/basys3_exam/basys3_exam.gen/sources_1/bd/soc_hello/ip/soc_hello_axi_smc_0/bd_0/ip/ip_34/bd_57e4_m01arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user16/workspace_vivado/basys3_exam/basys3_exam.gen/sources_1/bd/soc_hello/ip/soc_hello_axi_smc_0/bd_0/ip/ip_35/bd_57e4_m01rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user16/workspace_vivado/basys3_exam/basys3_exam.gen/sources_1/bd/soc_hello/ip/soc_hello_axi_smc_0/bd_0/ip/ip_36/bd_57e4_m01awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user16/workspace_vivado/basys3_exam/basys3_exam.gen/sources_1/bd/soc_hello/ip/soc_hello_axi_smc_0/bd_0/ip/ip_37/bd_57e4_m01wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user16/workspace_vivado/basys3_exam/basys3_exam.gen/sources_1/bd/soc_hello/ip/soc_hello_axi_smc_0/bd_0/ip/ip_38/bd_57e4_m01bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user16/workspace_vivado/basys3_exam/basys3_exam.gen/sources_1/bd/soc_hello/ip/soc_hello_axi_smc_0/bd_0/ip/ip_39/bd_57e4_m01e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: /home/user16/workspace_vivado/basys3_exam/basys3_exam.gen/sources_1/bd/soc_hello/ip/soc_hello_axi_smc_0/bd_0/ip/ip_1/bd_57e4_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/user16/workspace_vivado/basys3_exam/basys3_exam.gen/sources_1/bd/soc_hello/ip/soc_hello_axi_smc_0/bd_0/ip/ip_1/bd_57e4_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/user16/workspace_vivado/basys3_exam/basys3_exam.gen/sources_1/bd/soc_hello/ip/soc_hello_axi_smc_0/bd_0/ip/ip_2/bd_57e4_arinsw_0_ooc.xdc

# XDC: /home/user16/workspace_vivado/basys3_exam/basys3_exam.gen/sources_1/bd/soc_hello/ip/soc_hello_axi_smc_0/bd_0/ip/ip_3/bd_57e4_rinsw_0_ooc.xdc

# XDC: /home/user16/workspace_vivado/basys3_exam/basys3_exam.gen/sources_1/bd/soc_hello/ip/soc_hello_axi_smc_0/bd_0/ip/ip_4/bd_57e4_awinsw_0_ooc.xdc

# XDC: /home/user16/workspace_vivado/basys3_exam/basys3_exam.gen/sources_1/bd/soc_hello/ip/soc_hello_axi_smc_0/bd_0/ip/ip_5/bd_57e4_winsw_0_ooc.xdc

# XDC: /home/user16/workspace_vivado/basys3_exam/basys3_exam.gen/sources_1/bd/soc_hello/ip/soc_hello_axi_smc_0/bd_0/ip/ip_6/bd_57e4_binsw_0_ooc.xdc

# XDC: /home/user16/workspace_vivado/basys3_exam/basys3_exam.gen/sources_1/bd/soc_hello/ip/soc_hello_axi_smc_0/bd_0/ip/ip_7/bd_57e4_aroutsw_0_ooc.xdc

# XDC: /home/user16/workspace_vivado/basys3_exam/basys3_exam.gen/sources_1/bd/soc_hello/ip/soc_hello_axi_smc_0/bd_0/ip/ip_8/bd_57e4_routsw_0_ooc.xdc

# XDC: /home/user16/workspace_vivado/basys3_exam/basys3_exam.gen/sources_1/bd/soc_hello/ip/soc_hello_axi_smc_0/bd_0/ip/ip_9/bd_57e4_awoutsw_0_ooc.xdc

# XDC: /home/user16/workspace_vivado/basys3_exam/basys3_exam.gen/sources_1/bd/soc_hello/ip/soc_hello_axi_smc_0/bd_0/ip/ip_10/bd_57e4_woutsw_0_ooc.xdc

# XDC: /home/user16/workspace_vivado/basys3_exam/basys3_exam.gen/sources_1/bd/soc_hello/ip/soc_hello_axi_smc_0/bd_0/ip/ip_11/bd_57e4_boutsw_0_ooc.xdc

# XDC: /home/user16/workspace_vivado/basys3_exam/basys3_exam.gen/sources_1/bd/soc_hello/ip/soc_hello_axi_smc_0/bd_0/ip/ip_12/bd_57e4_arni_0_ooc.xdc

# XDC: /home/user16/workspace_vivado/basys3_exam/basys3_exam.gen/sources_1/bd/soc_hello/ip/soc_hello_axi_smc_0/bd_0/ip/ip_13/bd_57e4_rni_0_ooc.xdc

# XDC: /home/user16/workspace_vivado/basys3_exam/basys3_exam.gen/sources_1/bd/soc_hello/ip/soc_hello_axi_smc_0/bd_0/ip/ip_14/bd_57e4_awni_0_ooc.xdc

# XDC: /home/user16/workspace_vivado/basys3_exam/basys3_exam.gen/sources_1/bd/soc_hello/ip/soc_hello_axi_smc_0/bd_0/ip/ip_15/bd_57e4_wni_0_ooc.xdc

# XDC: /home/user16/workspace_vivado/basys3_exam/basys3_exam.gen/sources_1/bd/soc_hello/ip/soc_hello_axi_smc_0/bd_0/ip/ip_16/bd_57e4_bni_0_ooc.xdc

# XDC: /home/user16/workspace_vivado/basys3_exam/basys3_exam.gen/sources_1/bd/soc_hello/ip/soc_hello_axi_smc_0/bd_0/ip/ip_20/bd_57e4_s00a2s_0_ooc.xdc

# XDC: /home/user16/workspace_vivado/basys3_exam/basys3_exam.gen/sources_1/bd/soc_hello/ip/soc_hello_axi_smc_0/bd_0/ip/ip_21/bd_57e4_sarn_0_ooc.xdc

# XDC: /home/user16/workspace_vivado/basys3_exam/basys3_exam.gen/sources_1/bd/soc_hello/ip/soc_hello_axi_smc_0/bd_0/ip/ip_22/bd_57e4_srn_0_ooc.xdc

# XDC: /home/user16/workspace_vivado/basys3_exam/basys3_exam.gen/sources_1/bd/soc_hello/ip/soc_hello_axi_smc_0/bd_0/ip/ip_23/bd_57e4_sawn_0_ooc.xdc

# XDC: /home/user16/workspace_vivado/basys3_exam/basys3_exam.gen/sources_1/bd/soc_hello/ip/soc_hello_axi_smc_0/bd_0/ip/ip_24/bd_57e4_swn_0_ooc.xdc

# XDC: /home/user16/workspace_vivado/basys3_exam/basys3_exam.gen/sources_1/bd/soc_hello/ip/soc_hello_axi_smc_0/bd_0/ip/ip_25/bd_57e4_sbn_0_ooc.xdc

# XDC: /home/user16/workspace_vivado/basys3_exam/basys3_exam.gen/sources_1/bd/soc_hello/ip/soc_hello_axi_smc_0/bd_0/ip/ip_26/bd_57e4_m00s2a_0_ooc.xdc

# XDC: /home/user16/workspace_vivado/basys3_exam/basys3_exam.gen/sources_1/bd/soc_hello/ip/soc_hello_axi_smc_0/bd_0/ip/ip_27/bd_57e4_m00arn_0_ooc.xdc

# XDC: /home/user16/workspace_vivado/basys3_exam/basys3_exam.gen/sources_1/bd/soc_hello/ip/soc_hello_axi_smc_0/bd_0/ip/ip_28/bd_57e4_m00rn_0_ooc.xdc

# XDC: /home/user16/workspace_vivado/basys3_exam/basys3_exam.gen/sources_1/bd/soc_hello/ip/soc_hello_axi_smc_0/bd_0/ip/ip_29/bd_57e4_m00awn_0_ooc.xdc

# XDC: /home/user16/workspace_vivado/basys3_exam/basys3_exam.gen/sources_1/bd/soc_hello/ip/soc_hello_axi_smc_0/bd_0/ip/ip_30/bd_57e4_m00wn_0_ooc.xdc

# XDC: /home/user16/workspace_vivado/basys3_exam/basys3_exam.gen/sources_1/bd/soc_hello/ip/soc_hello_axi_smc_0/bd_0/ip/ip_31/bd_57e4_m00bn_0_ooc.xdc

# XDC: /home/user16/workspace_vivado/basys3_exam/basys3_exam.gen/sources_1/bd/soc_hello/ip/soc_hello_axi_smc_0/bd_0/ip/ip_33/bd_57e4_m01s2a_0_ooc.xdc

# XDC: /home/user16/workspace_vivado/basys3_exam/basys3_exam.gen/sources_1/bd/soc_hello/ip/soc_hello_axi_smc_0/bd_0/ip/ip_34/bd_57e4_m01arn_0_ooc.xdc

# XDC: /home/user16/workspace_vivado/basys3_exam/basys3_exam.gen/sources_1/bd/soc_hello/ip/soc_hello_axi_smc_0/bd_0/ip/ip_35/bd_57e4_m01rn_0_ooc.xdc

# XDC: /home/user16/workspace_vivado/basys3_exam/basys3_exam.gen/sources_1/bd/soc_hello/ip/soc_hello_axi_smc_0/bd_0/ip/ip_36/bd_57e4_m01awn_0_ooc.xdc

# XDC: /home/user16/workspace_vivado/basys3_exam/basys3_exam.gen/sources_1/bd/soc_hello/ip/soc_hello_axi_smc_0/bd_0/ip/ip_37/bd_57e4_m01wn_0_ooc.xdc

# XDC: /home/user16/workspace_vivado/basys3_exam/basys3_exam.gen/sources_1/bd/soc_hello/ip/soc_hello_axi_smc_0/bd_0/ip/ip_38/bd_57e4_m01bn_0_ooc.xdc

# XDC: /home/user16/workspace_vivado/basys3_exam/basys3_exam.gen/sources_1/bd/soc_hello/ip/soc_hello_axi_smc_0/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'soc_hello_axi_smc_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/user16/workspace_vivado/basys3_exam/basys3_exam.gen/sources_1/bd/soc_hello/ip/soc_hello_axi_smc_0/smartconnect.xdc
# XDC: The top module name and the constraint reference have the same name: 'soc_hello_axi_smc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/user16/workspace_vivado/basys3_exam/basys3_exam.srcs/sources_1/bd/soc_hello/ip/soc_hello_axi_smc_0/soc_hello_axi_smc_0.xci
# IP: The module: 'soc_hello_axi_smc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: /home/user16/workspace_vivado/basys3_exam/basys3_exam.gen/sources_1/bd/soc_hello/ip/soc_hello_axi_smc_0/bd_0/bd_57e4.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user16/workspace_vivado/basys3_exam/basys3_exam.gen/sources_1/bd/soc_hello/ip/soc_hello_axi_smc_0/bd_0/ip/ip_0/bd_57e4_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user16/workspace_vivado/basys3_exam/basys3_exam.gen/sources_1/bd/soc_hello/ip/soc_hello_axi_smc_0/bd_0/ip/ip_1/bd_57e4_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user16/workspace_vivado/basys3_exam/basys3_exam.gen/sources_1/bd/soc_hello/ip/soc_hello_axi_smc_0/bd_0/ip/ip_2/bd_57e4_arinsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user16/workspace_vivado/basys3_exam/basys3_exam.gen/sources_1/bd/soc_hello/ip/soc_hello_axi_smc_0/bd_0/ip/ip_3/bd_57e4_rinsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user16/workspace_vivado/basys3_exam/basys3_exam.gen/sources_1/bd/soc_hello/ip/soc_hello_axi_smc_0/bd_0/ip/ip_4/bd_57e4_awinsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user16/workspace_vivado/basys3_exam/basys3_exam.gen/sources_1/bd/soc_hello/ip/soc_hello_axi_smc_0/bd_0/ip/ip_5/bd_57e4_winsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user16/workspace_vivado/basys3_exam/basys3_exam.gen/sources_1/bd/soc_hello/ip/soc_hello_axi_smc_0/bd_0/ip/ip_6/bd_57e4_binsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user16/workspace_vivado/basys3_exam/basys3_exam.gen/sources_1/bd/soc_hello/ip/soc_hello_axi_smc_0/bd_0/ip/ip_7/bd_57e4_aroutsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user16/workspace_vivado/basys3_exam/basys3_exam.gen/sources_1/bd/soc_hello/ip/soc_hello_axi_smc_0/bd_0/ip/ip_8/bd_57e4_routsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user16/workspace_vivado/basys3_exam/basys3_exam.gen/sources_1/bd/soc_hello/ip/soc_hello_axi_smc_0/bd_0/ip/ip_9/bd_57e4_awoutsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user16/workspace_vivado/basys3_exam/basys3_exam.gen/sources_1/bd/soc_hello/ip/soc_hello_axi_smc_0/bd_0/ip/ip_10/bd_57e4_woutsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user16/workspace_vivado/basys3_exam/basys3_exam.gen/sources_1/bd/soc_hello/ip/soc_hello_axi_smc_0/bd_0/ip/ip_11/bd_57e4_boutsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user16/workspace_vivado/basys3_exam/basys3_exam.gen/sources_1/bd/soc_hello/ip/soc_hello_axi_smc_0/bd_0/ip/ip_12/bd_57e4_arni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user16/workspace_vivado/basys3_exam/basys3_exam.gen/sources_1/bd/soc_hello/ip/soc_hello_axi_smc_0/bd_0/ip/ip_13/bd_57e4_rni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user16/workspace_vivado/basys3_exam/basys3_exam.gen/sources_1/bd/soc_hello/ip/soc_hello_axi_smc_0/bd_0/ip/ip_14/bd_57e4_awni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user16/workspace_vivado/basys3_exam/basys3_exam.gen/sources_1/bd/soc_hello/ip/soc_hello_axi_smc_0/bd_0/ip/ip_15/bd_57e4_wni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user16/workspace_vivado/basys3_exam/basys3_exam.gen/sources_1/bd/soc_hello/ip/soc_hello_axi_smc_0/bd_0/ip/ip_16/bd_57e4_bni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user16/workspace_vivado/basys3_exam/basys3_exam.gen/sources_1/bd/soc_hello/ip/soc_hello_axi_smc_0/bd_0/ip/ip_17/bd_57e4_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user16/workspace_vivado/basys3_exam/basys3_exam.gen/sources_1/bd/soc_hello/ip/soc_hello_axi_smc_0/bd_0/ip/ip_18/bd_57e4_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user16/workspace_vivado/basys3_exam/basys3_exam.gen/sources_1/bd/soc_hello/ip/soc_hello_axi_smc_0/bd_0/ip/ip_19/bd_57e4_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user16/workspace_vivado/basys3_exam/basys3_exam.gen/sources_1/bd/soc_hello/ip/soc_hello_axi_smc_0/bd_0/ip/ip_20/bd_57e4_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user16/workspace_vivado/basys3_exam/basys3_exam.gen/sources_1/bd/soc_hello/ip/soc_hello_axi_smc_0/bd_0/ip/ip_21/bd_57e4_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user16/workspace_vivado/basys3_exam/basys3_exam.gen/sources_1/bd/soc_hello/ip/soc_hello_axi_smc_0/bd_0/ip/ip_22/bd_57e4_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user16/workspace_vivado/basys3_exam/basys3_exam.gen/sources_1/bd/soc_hello/ip/soc_hello_axi_smc_0/bd_0/ip/ip_23/bd_57e4_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user16/workspace_vivado/basys3_exam/basys3_exam.gen/sources_1/bd/soc_hello/ip/soc_hello_axi_smc_0/bd_0/ip/ip_24/bd_57e4_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user16/workspace_vivado/basys3_exam/basys3_exam.gen/sources_1/bd/soc_hello/ip/soc_hello_axi_smc_0/bd_0/ip/ip_25/bd_57e4_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user16/workspace_vivado/basys3_exam/basys3_exam.gen/sources_1/bd/soc_hello/ip/soc_hello_axi_smc_0/bd_0/ip/ip_26/bd_57e4_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user16/workspace_vivado/basys3_exam/basys3_exam.gen/sources_1/bd/soc_hello/ip/soc_hello_axi_smc_0/bd_0/ip/ip_27/bd_57e4_m00arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user16/workspace_vivado/basys3_exam/basys3_exam.gen/sources_1/bd/soc_hello/ip/soc_hello_axi_smc_0/bd_0/ip/ip_28/bd_57e4_m00rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user16/workspace_vivado/basys3_exam/basys3_exam.gen/sources_1/bd/soc_hello/ip/soc_hello_axi_smc_0/bd_0/ip/ip_29/bd_57e4_m00awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user16/workspace_vivado/basys3_exam/basys3_exam.gen/sources_1/bd/soc_hello/ip/soc_hello_axi_smc_0/bd_0/ip/ip_30/bd_57e4_m00wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user16/workspace_vivado/basys3_exam/basys3_exam.gen/sources_1/bd/soc_hello/ip/soc_hello_axi_smc_0/bd_0/ip/ip_31/bd_57e4_m00bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user16/workspace_vivado/basys3_exam/basys3_exam.gen/sources_1/bd/soc_hello/ip/soc_hello_axi_smc_0/bd_0/ip/ip_32/bd_57e4_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user16/workspace_vivado/basys3_exam/basys3_exam.gen/sources_1/bd/soc_hello/ip/soc_hello_axi_smc_0/bd_0/ip/ip_33/bd_57e4_m01s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user16/workspace_vivado/basys3_exam/basys3_exam.gen/sources_1/bd/soc_hello/ip/soc_hello_axi_smc_0/bd_0/ip/ip_34/bd_57e4_m01arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user16/workspace_vivado/basys3_exam/basys3_exam.gen/sources_1/bd/soc_hello/ip/soc_hello_axi_smc_0/bd_0/ip/ip_35/bd_57e4_m01rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user16/workspace_vivado/basys3_exam/basys3_exam.gen/sources_1/bd/soc_hello/ip/soc_hello_axi_smc_0/bd_0/ip/ip_36/bd_57e4_m01awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user16/workspace_vivado/basys3_exam/basys3_exam.gen/sources_1/bd/soc_hello/ip/soc_hello_axi_smc_0/bd_0/ip/ip_37/bd_57e4_m01wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user16/workspace_vivado/basys3_exam/basys3_exam.gen/sources_1/bd/soc_hello/ip/soc_hello_axi_smc_0/bd_0/ip/ip_38/bd_57e4_m01bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user16/workspace_vivado/basys3_exam/basys3_exam.gen/sources_1/bd/soc_hello/ip/soc_hello_axi_smc_0/bd_0/ip/ip_39/bd_57e4_m01e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: /home/user16/workspace_vivado/basys3_exam/basys3_exam.gen/sources_1/bd/soc_hello/ip/soc_hello_axi_smc_0/bd_0/ip/ip_1/bd_57e4_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/user16/workspace_vivado/basys3_exam/basys3_exam.gen/sources_1/bd/soc_hello/ip/soc_hello_axi_smc_0/bd_0/ip/ip_1/bd_57e4_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/user16/workspace_vivado/basys3_exam/basys3_exam.gen/sources_1/bd/soc_hello/ip/soc_hello_axi_smc_0/bd_0/ip/ip_2/bd_57e4_arinsw_0_ooc.xdc

# XDC: /home/user16/workspace_vivado/basys3_exam/basys3_exam.gen/sources_1/bd/soc_hello/ip/soc_hello_axi_smc_0/bd_0/ip/ip_3/bd_57e4_rinsw_0_ooc.xdc

# XDC: /home/user16/workspace_vivado/basys3_exam/basys3_exam.gen/sources_1/bd/soc_hello/ip/soc_hello_axi_smc_0/bd_0/ip/ip_4/bd_57e4_awinsw_0_ooc.xdc

# XDC: /home/user16/workspace_vivado/basys3_exam/basys3_exam.gen/sources_1/bd/soc_hello/ip/soc_hello_axi_smc_0/bd_0/ip/ip_5/bd_57e4_winsw_0_ooc.xdc

# XDC: /home/user16/workspace_vivado/basys3_exam/basys3_exam.gen/sources_1/bd/soc_hello/ip/soc_hello_axi_smc_0/bd_0/ip/ip_6/bd_57e4_binsw_0_ooc.xdc

# XDC: /home/user16/workspace_vivado/basys3_exam/basys3_exam.gen/sources_1/bd/soc_hello/ip/soc_hello_axi_smc_0/bd_0/ip/ip_7/bd_57e4_aroutsw_0_ooc.xdc

# XDC: /home/user16/workspace_vivado/basys3_exam/basys3_exam.gen/sources_1/bd/soc_hello/ip/soc_hello_axi_smc_0/bd_0/ip/ip_8/bd_57e4_routsw_0_ooc.xdc

# XDC: /home/user16/workspace_vivado/basys3_exam/basys3_exam.gen/sources_1/bd/soc_hello/ip/soc_hello_axi_smc_0/bd_0/ip/ip_9/bd_57e4_awoutsw_0_ooc.xdc

# XDC: /home/user16/workspace_vivado/basys3_exam/basys3_exam.gen/sources_1/bd/soc_hello/ip/soc_hello_axi_smc_0/bd_0/ip/ip_10/bd_57e4_woutsw_0_ooc.xdc

# XDC: /home/user16/workspace_vivado/basys3_exam/basys3_exam.gen/sources_1/bd/soc_hello/ip/soc_hello_axi_smc_0/bd_0/ip/ip_11/bd_57e4_boutsw_0_ooc.xdc

# XDC: /home/user16/workspace_vivado/basys3_exam/basys3_exam.gen/sources_1/bd/soc_hello/ip/soc_hello_axi_smc_0/bd_0/ip/ip_12/bd_57e4_arni_0_ooc.xdc

# XDC: /home/user16/workspace_vivado/basys3_exam/basys3_exam.gen/sources_1/bd/soc_hello/ip/soc_hello_axi_smc_0/bd_0/ip/ip_13/bd_57e4_rni_0_ooc.xdc

# XDC: /home/user16/workspace_vivado/basys3_exam/basys3_exam.gen/sources_1/bd/soc_hello/ip/soc_hello_axi_smc_0/bd_0/ip/ip_14/bd_57e4_awni_0_ooc.xdc

# XDC: /home/user16/workspace_vivado/basys3_exam/basys3_exam.gen/sources_1/bd/soc_hello/ip/soc_hello_axi_smc_0/bd_0/ip/ip_15/bd_57e4_wni_0_ooc.xdc

# XDC: /home/user16/workspace_vivado/basys3_exam/basys3_exam.gen/sources_1/bd/soc_hello/ip/soc_hello_axi_smc_0/bd_0/ip/ip_16/bd_57e4_bni_0_ooc.xdc

# XDC: /home/user16/workspace_vivado/basys3_exam/basys3_exam.gen/sources_1/bd/soc_hello/ip/soc_hello_axi_smc_0/bd_0/ip/ip_20/bd_57e4_s00a2s_0_ooc.xdc

# XDC: /home/user16/workspace_vivado/basys3_exam/basys3_exam.gen/sources_1/bd/soc_hello/ip/soc_hello_axi_smc_0/bd_0/ip/ip_21/bd_57e4_sarn_0_ooc.xdc

# XDC: /home/user16/workspace_vivado/basys3_exam/basys3_exam.gen/sources_1/bd/soc_hello/ip/soc_hello_axi_smc_0/bd_0/ip/ip_22/bd_57e4_srn_0_ooc.xdc

# XDC: /home/user16/workspace_vivado/basys3_exam/basys3_exam.gen/sources_1/bd/soc_hello/ip/soc_hello_axi_smc_0/bd_0/ip/ip_23/bd_57e4_sawn_0_ooc.xdc

# XDC: /home/user16/workspace_vivado/basys3_exam/basys3_exam.gen/sources_1/bd/soc_hello/ip/soc_hello_axi_smc_0/bd_0/ip/ip_24/bd_57e4_swn_0_ooc.xdc

# XDC: /home/user16/workspace_vivado/basys3_exam/basys3_exam.gen/sources_1/bd/soc_hello/ip/soc_hello_axi_smc_0/bd_0/ip/ip_25/bd_57e4_sbn_0_ooc.xdc

# XDC: /home/user16/workspace_vivado/basys3_exam/basys3_exam.gen/sources_1/bd/soc_hello/ip/soc_hello_axi_smc_0/bd_0/ip/ip_26/bd_57e4_m00s2a_0_ooc.xdc

# XDC: /home/user16/workspace_vivado/basys3_exam/basys3_exam.gen/sources_1/bd/soc_hello/ip/soc_hello_axi_smc_0/bd_0/ip/ip_27/bd_57e4_m00arn_0_ooc.xdc

# XDC: /home/user16/workspace_vivado/basys3_exam/basys3_exam.gen/sources_1/bd/soc_hello/ip/soc_hello_axi_smc_0/bd_0/ip/ip_28/bd_57e4_m00rn_0_ooc.xdc

# XDC: /home/user16/workspace_vivado/basys3_exam/basys3_exam.gen/sources_1/bd/soc_hello/ip/soc_hello_axi_smc_0/bd_0/ip/ip_29/bd_57e4_m00awn_0_ooc.xdc

# XDC: /home/user16/workspace_vivado/basys3_exam/basys3_exam.gen/sources_1/bd/soc_hello/ip/soc_hello_axi_smc_0/bd_0/ip/ip_30/bd_57e4_m00wn_0_ooc.xdc

# XDC: /home/user16/workspace_vivado/basys3_exam/basys3_exam.gen/sources_1/bd/soc_hello/ip/soc_hello_axi_smc_0/bd_0/ip/ip_31/bd_57e4_m00bn_0_ooc.xdc

# XDC: /home/user16/workspace_vivado/basys3_exam/basys3_exam.gen/sources_1/bd/soc_hello/ip/soc_hello_axi_smc_0/bd_0/ip/ip_33/bd_57e4_m01s2a_0_ooc.xdc

# XDC: /home/user16/workspace_vivado/basys3_exam/basys3_exam.gen/sources_1/bd/soc_hello/ip/soc_hello_axi_smc_0/bd_0/ip/ip_34/bd_57e4_m01arn_0_ooc.xdc

# XDC: /home/user16/workspace_vivado/basys3_exam/basys3_exam.gen/sources_1/bd/soc_hello/ip/soc_hello_axi_smc_0/bd_0/ip/ip_35/bd_57e4_m01rn_0_ooc.xdc

# XDC: /home/user16/workspace_vivado/basys3_exam/basys3_exam.gen/sources_1/bd/soc_hello/ip/soc_hello_axi_smc_0/bd_0/ip/ip_36/bd_57e4_m01awn_0_ooc.xdc

# XDC: /home/user16/workspace_vivado/basys3_exam/basys3_exam.gen/sources_1/bd/soc_hello/ip/soc_hello_axi_smc_0/bd_0/ip/ip_37/bd_57e4_m01wn_0_ooc.xdc

# XDC: /home/user16/workspace_vivado/basys3_exam/basys3_exam.gen/sources_1/bd/soc_hello/ip/soc_hello_axi_smc_0/bd_0/ip/ip_38/bd_57e4_m01bn_0_ooc.xdc

# XDC: /home/user16/workspace_vivado/basys3_exam/basys3_exam.gen/sources_1/bd/soc_hello/ip/soc_hello_axi_smc_0/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'soc_hello_axi_smc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/user16/workspace_vivado/basys3_exam/basys3_exam.gen/sources_1/bd/soc_hello/ip/soc_hello_axi_smc_0/smartconnect.xdc
# XDC: The top module name and the constraint reference have the same name: 'soc_hello_axi_smc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
