# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/user16/workspace_vivado/basys3_exam/basys3_exam.srcs/sources_1/bd/soc_btn_fnd/ip/soc_btn_fnd_axi_gpio_1_0/soc_btn_fnd_axi_gpio_1_0.xci
# IP: The module: 'soc_btn_fnd_axi_gpio_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/user16/workspace_vivado/basys3_exam/basys3_exam.gen/sources_1/bd/soc_btn_fnd/ip/soc_btn_fnd_axi_gpio_1_0/soc_btn_fnd_axi_gpio_1_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'soc_btn_fnd_axi_gpio_1_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/user16/workspace_vivado/basys3_exam/basys3_exam.gen/sources_1/bd/soc_btn_fnd/ip/soc_btn_fnd_axi_gpio_1_0/soc_btn_fnd_axi_gpio_1_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'soc_btn_fnd_axi_gpio_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/user16/workspace_vivado/basys3_exam/basys3_exam.gen/sources_1/bd/soc_btn_fnd/ip/soc_btn_fnd_axi_gpio_1_0/soc_btn_fnd_axi_gpio_1_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'soc_btn_fnd_axi_gpio_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /home/user16/workspace_vivado/basys3_exam/basys3_exam.srcs/sources_1/bd/soc_btn_fnd/ip/soc_btn_fnd_axi_gpio_1_0/soc_btn_fnd_axi_gpio_1_0.xci
# IP: The module: 'soc_btn_fnd_axi_gpio_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/user16/workspace_vivado/basys3_exam/basys3_exam.gen/sources_1/bd/soc_btn_fnd/ip/soc_btn_fnd_axi_gpio_1_0/soc_btn_fnd_axi_gpio_1_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'soc_btn_fnd_axi_gpio_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/user16/workspace_vivado/basys3_exam/basys3_exam.gen/sources_1/bd/soc_btn_fnd/ip/soc_btn_fnd_axi_gpio_1_0/soc_btn_fnd_axi_gpio_1_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'soc_btn_fnd_axi_gpio_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/user16/workspace_vivado/basys3_exam/basys3_exam.gen/sources_1/bd/soc_btn_fnd/ip/soc_btn_fnd_axi_gpio_1_0/soc_btn_fnd_axi_gpio_1_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'soc_btn_fnd_axi_gpio_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
