#!/usr/bin/env bash
# ****************************************************************************
# Vivado (TM) v2024.2 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : AMD Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Fri Sep 19 11:37:14 KST 2025
# SW Build 5239630 on Fri Nov 08 22:34:34 MST 2024
#
# Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
# Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim stepper_cntr_behav -key {Behavioral:sim_1:Functional:stepper_cntr} -tclbatch stepper_cntr.tcl -protoinst "protoinst_files/bd_85ae.protoinst" -protoinst "protoinst_files/soc_rtc_read.protoinst" -protoinst "protoinst_files/soc_servo180.protoinst" -protoinst "protoinst_files/soc_intc_stopwatch.protoinst" -protoinst "protoinst_files/soc_intc.protoinst" -protoinst "protoinst_files/bd_fdbf.protoinst" -protoinst "protoinst_files/soc_pwm.protoinst" -protoinst "protoinst_files/bd_1d9d.protoinst" -protoinst "protoinst_files/soc_pwm_4096step.protoinst" -protoinst "protoinst_files/bd_2391.protoinst" -protoinst "protoinst_files/soc_watch.protoinst" -protoinst "protoinst_files/bd_ebb4.protoinst" -protoinst "protoinst_files/soc_ultrasonic.protoinst" -protoinst "protoinst_files/bd_5040.protoinst" -protoinst "protoinst_files/soc_txtlcd.protoinst" -protoinst "protoinst_files/bd_b74d.protoinst" -protoinst "protoinst_files/soc_stop_watch.protoinst" -protoinst "protoinst_files/bd_370f.protoinst" -protoinst "protoinst_files/soc_keypad.protoinst" -protoinst "protoinst_files/bd_57e4.protoinst" -protoinst "protoinst_files/soc_hello.protoinst" -protoinst "protoinst_files/bd_bddd.protoinst" -protoinst "protoinst_files/soc_dht11.protoinst" -protoinst "protoinst_files/bd_f5a2.protoinst" -protoinst "protoinst_files/soc_dht11_i2c.protoinst" -protoinst "protoinst_files/bd_a70c.protoinst" -protoinst "protoinst_files/soc_btn_fnd.protoinst" -log simulate.log"
xsim stepper_cntr_behav -key {Behavioral:sim_1:Functional:stepper_cntr} -tclbatch stepper_cntr.tcl -protoinst "protoinst_files/bd_85ae.protoinst" -protoinst "protoinst_files/soc_rtc_read.protoinst" -protoinst "protoinst_files/soc_servo180.protoinst" -protoinst "protoinst_files/soc_intc_stopwatch.protoinst" -protoinst "protoinst_files/soc_intc.protoinst" -protoinst "protoinst_files/bd_fdbf.protoinst" -protoinst "protoinst_files/soc_pwm.protoinst" -protoinst "protoinst_files/bd_1d9d.protoinst" -protoinst "protoinst_files/soc_pwm_4096step.protoinst" -protoinst "protoinst_files/bd_2391.protoinst" -protoinst "protoinst_files/soc_watch.protoinst" -protoinst "protoinst_files/bd_ebb4.protoinst" -protoinst "protoinst_files/soc_ultrasonic.protoinst" -protoinst "protoinst_files/bd_5040.protoinst" -protoinst "protoinst_files/soc_txtlcd.protoinst" -protoinst "protoinst_files/bd_b74d.protoinst" -protoinst "protoinst_files/soc_stop_watch.protoinst" -protoinst "protoinst_files/bd_370f.protoinst" -protoinst "protoinst_files/soc_keypad.protoinst" -protoinst "protoinst_files/bd_57e4.protoinst" -protoinst "protoinst_files/soc_hello.protoinst" -protoinst "protoinst_files/bd_bddd.protoinst" -protoinst "protoinst_files/soc_dht11.protoinst" -protoinst "protoinst_files/bd_f5a2.protoinst" -protoinst "protoinst_files/soc_dht11_i2c.protoinst" -protoinst "protoinst_files/bd_a70c.protoinst" -protoinst "protoinst_files/soc_btn_fnd.protoinst" -log simulate.log

